// The try and catch statements handle exceptions in a standard way which is provided by JavaScript. 
// However, you can use the throw statement to pass user-defined exceptions.

const number = 40;
try {
    if(number > 50) {
        console.log('Success');
    }
    else {

        // user-defined throw statement
        throw new Error('The number is low');
    }

    // if throw executes, the below code does not execute
    console.log('hello');
}
catch(error) {
    console.log('An error caught'); 
    console.log('Error message: ' + error);  
}